language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t  sportnoi/dockerfrontend -f Dockerfile.dev . 

script:
  - docker run -e CI=true sportnoi/dockerfrontend npm run test
